# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='clouds',
            fields=[
                ('clouds_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('N', models.IntegerField()),
                ('Cl', models.CharField(max_length=100)),
                ('Nh', models.IntegerField()),
                ('H', models.CharField(max_length=100)),
                ('Cm', models.CharField(max_length=100)),
                ('Ch', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'clouds',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('T', models.FloatField()),
                ('P', models.FloatField()),
                ('U', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'forecast',
            },
        ),
        migrations.CreateModel(
            name='other_weather_data',
            fields=[
                ('other_weather_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('U', models.IntegerField()),
                ('VV', models.FloatField()),
                ('RRR', models.CharField(max_length=45)),
                ('tR', models.IntegerField()),
                ('E', models.CharField(max_length=45)),
                ('E1', models.CharField(max_length=45)),
                ('sss', models.CharField(max_length=45)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'other_weather_data',
            },
        ),
        migrations.CreateModel(
            name='pressure',
            fields=[
                ('pressure_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('P0', models.FloatField()),
                ('P', models.FloatField()),
                ('Pa', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'pressure',
            },
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('temperature_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('T', models.FloatField()),
                ('Tn', models.FloatField()),
                ('Tx', models.FloatField()),
                ('Td', models.FloatField()),
                ('Tg', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('WW', models.CharField(max_length=100)),
                ('W1', models.CharField(max_length=100)),
                ('W2', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'weather',
            },
        ),
        migrations.CreateModel(
            name='wind',
            fields=[
                ('wind_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('DD', models.CharField(max_length=45)),
                ('Ff', models.CharField(max_length=45)),
                ('ff10', models.FloatField()),
                ('ff3', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.city')),
            ],
            options={
                'db_table': 'wind',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.country'),
        ),
        migrations.AlterUniqueTogether(
            name='wind',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='pressure',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='other_weather_data',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set([('date', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='clouds',
            unique_together=set([('date', 'city')]),
        ),
    ]
